# config.py
SERVER_IP = '127.0.0.1'
SERVER_PORT = 23232
MAX_ROOMS = 1
MAX_CONNECTIONS = 5

SERVER_CODES = {
      0: "OK",
      1: "NOT_IMPLEMENTED",
      2: "ROOM_FULL",
      3: "NOT_AUTHORIZED",
      4: "ILLEGAL_ACTION",
      5: "INTERNAL_ERROR",
    128: "HANDSHAKE_OK",
    129: "PROTOCOL_NOT_SUPPORTED",
    130: "SERVER_FULL",
}