

# SERVER PACKET CODES:
# LOGIN_RESPONSE = b"\x01" # 1
# REGISTER_RESPONSE = b"\x02" # 2
# REQUEST_GAME_LIST_RESPONSE = b"\x03" # 3
# JOIN_GAME_RESPONSE = b"\x04" # 4

CHAT_MESSAGE = 0
LOGIN_REQUEST = LOGIN_RESPONSE = 1
REGISTER_REQUEST = REGISTER_RESPONSE = 2

REQUEST_GAME_LIST = REQUEST_GAME_LIST_RESPONSE = 3
JOIN_GAME = JOIN_GAME_RESPONSE = 4