import logging

logger = logging.getLogger("server")


def send(client):...
# def callback_request():...
def broadcast():...
def send_deltas(n, client):...
    """send n number of last game events to the client"""