# CONFIG
TILE_SIZE = 32
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_CAPTION = "PaperWars"
MAX_FPS = 60
SDL_WINDOW_POS_X = 650
SDL_WINDOW_POS_Y = 30
DEFAULT_ZOOM = 1.0
ASSETS_PATH = "winclient/assets"
LOCAL_SERVER_URL = "http://localhost:5000"
PRODUCTION_SERVER_URL = "https://paperwars.herokuapp.com"

# COLORS
BACKGROUND_COLOR = (0, 128, 0)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)
COLOR_BLUE = (0, 0, 25)

# SCENES
MAIN_MENU_SCENE = 0
MULTIPLAYER_GAME_SCENE = 1 